READMEs: Update + fix typos + reformat
GoogleCloudPlatform/jenkernetes pull request #18
Opened 2017-01-05 18:36 UTC by ace-n

2017-01-05 22:38 UTC, waprin requested changes
Look good, let's clean up a few of those beta commands then we'll merge. Thanks for taking a a pass at this, definitely will still need a bit more work.

2017-01-05 22:38 UTC, waprin commented on README.md
>  * `gcloud beta container clusters create jenkins`
we can take out beta now

2017-01-05 22:38 UTC, waprin commented on README.md
take out beta here too

2017-01-05 22:38 UTC, waprin commented on README.md
>  * `./create_and_format_disk.sh`
This is no longer necessary

2017-01-05 22:38 UTC, waprin commented on setup/master/README.md
> +   Alternatively if you want to maximize uptime in the event of pod deletion, you can create a [replication controller](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/replication-
we need to switch this from replication controller to deployment but its ok for now

2018-04-12 16:02 UTC, tswast commented
FYI: I'm merging this so we can archive this repo in a somewhat better state.

2018-04-12 16:02 UTC, merged